services:

  ollama:
    image: ollama/ollama
    volumes:
      - ds-pub-ollama:/root/.ollama
    ports:
      - 11434:11434
  
  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000

  python-client:
    build:
      context: .
    container_name: ds-vector-python
    volumes:
      - ./scripts/:/opt/scripts/
    working_dir: /opt/scripts
    ports:
      - 127.0.0.1:8888:8888
    command: jupyter lab --allow-root --ip 0.0.0.0 --no-browser --NotebookApp.token=""  notebook.ipynb


volumes:
  ds-pub-ollama:
    driver: local
  chroma-data:
    driver: local